pipeline {
    agent {
        label 'AGENT-1'
    }

    options {
        disableConcurrentBuilds()
        ansiColor('xterm')     
        timeout(time: 30, unit: 'MINUTES')
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }

    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 08ecr
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """
                }
            }
        }

        stage('Apply or Destroy') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 08ecr
                        if [ "${params.ACTION}" == "apply" ]; then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" == "destroy" ]; then 
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }

    post {
        always {
            echo "This stage will always run"
            deleteDir()
        }
        success {
            echo "This stage will run when pipeline succeeds"
        }
        failure {
            echo "This stage will run when pipeline fails"
        }
    }
}
