pipeline{
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, value: 'MINUTES')
        ansicolour('xterm')
        disableConcurrentBuilds()
    }
    parameters{
        choice(name: 'ACTION', choices: ['Apply and destroy'], description: 'Select Action')
    }
    stages{
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                    cd 02Sg
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Apply or Destroy'){
            input {
                message "should we continue ${params.ACTION}"
                ok "Yes, we should."

            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 02Sg
                        if [ ${params.ACTION} == 'apply' ]
                        then 
                            terraform apply -auto-approve tfplan
                        elif [ ${params.ACTION} == 'destroy']
                        then
                            terraform destroy -auto-approve
                        fi
                        """
                }
            }
        }
    }
    post {
        always {
            echo "this section will run always"
            deleteDir()

        }
        sucess{
            echo "this section will run when pipeline is sucess"
        }
        failure {
            echo "this section will run when pipeline is failure"
        }
    }
}